export type Brand = "ELFBAR" | "Lost Mary" | "Fumot" | "JNR" | "Vozol";
export type Kind = "Disposable" | "E-Liquid" | "Pod System";
export type Stock = "in" | "limited" | "out";
export type Badge = "NEW" | "LOW" | "OUT";

export interface Product {
  id: string;
  name: string;
  brand: Brand;
  kind: Kind;
  badge?: Badge;
  desc: string;
  options: string[];
  optionLabel: "FLAVOR" | "NICOTINE";
  specs: [string, string][];
  stock: Stock;
  image?: string;
  puffs?: string;
}

export const CATEGORIES = ["All", "ELFBAR", "Lost Mary", "Fumot", "JNR", "Vozol"] as const;
export type Filter = (typeof CATEGORIES)[number];

const nic = ["0%", "2%", "3%", "5%"];
const img = (id: string) => `/products/${id}.webp`;

function unique(list: string[]) {
  const seen = new Set<string>();
  return list.filter((x) => {
    const k = x.toLowerCase();
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

export const PRODUCTS: Product[] = [
  {
    id: "elfbar-bc45000",
    name: "ELFBAR BC45000",
    brand: "ELFBAR",
    kind: "Disposable",
    badge: "NEW",
    desc: "Flagship 45K puff disposable with a full fruit-and-ice lineup. Mesh coil, rechargeable, 5% nicotine.",
    options: unique([
      "Watermelon Ice",
      "Strawberry Grapefruit",
      "Sour Apple Kiwi",
      "Red Raspberry Strawberry",
      "Pomegranate Raspberry Lime",
      "Pear Soda",
      "Lemon Lime",
      "Kiwi Pineapple Peach",
      "Grapefruit Green Tea",
      "Double Mint",
      "Cherry Peach Soda",
      "Blue Razz Ice",
      "Blackcurrant Grape",
      "Blackberry Lemonade",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "45,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-bc45000"),
    puffs: "45K",
  },
  {
    id: "elfbar-lush-king-pro-40k",
    name: "ELFBAR Lush King Pro 40K",
    brand: "ELFBAR",
    kind: "Disposable",
    desc: "Lush King Pro with a 40K puff rating and a mix of tea, cactus, mint and tropical ice flavors.",
    options: unique([
      "Black Currant Pineapple",
      "Milky Oolong",
      "Cucumber Lime",
      "Starfruit Grape",
      "Cactus Lime",
      "Cherry Burst",
      "Mountain Mint",
      "Sour Pineapple Ice",
      "Tropical Mango",
      "Sour Strawberry Dragonfruit",
      "Pomegranate Burst",
      "Sour Apple Ice",
      "Black Grape Ice",
      "Blue Razz Ice",
      "Watermelon Ice",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-lush-king-pro-40k"),
    puffs: "40K",
  },
  {
    id: "elfbar-moonnight-40k",
    name: "ELFBAR MoonNight 40K",
    brand: "ELFBAR",
    kind: "Disposable",
    desc: "MoonNight 40K — compact high-puff bar with grape, cola, mint and tropical mixes.",
    options: unique([
      "Grape Ice",
      "Lime Cola",
      "Grape Raspberry",
      "Lemon Lime",
      "Kiwi Passion Fruit Guava",
      "Cherry Watermelon",
      "Pomegranate Burst",
      "Peach Ice",
      "Blue Razz Ice",
      "Watermelon Ice",
      "Miami Mint",
      "Mango Peach Watermelon",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-moonnight-40k"),
    puffs: "40K",
  },
  {
    id: "elfbar-raya-d3-25k",
    name: "ELFBAR RAYA D3 25K",
    brand: "ELFBAR",
    kind: "Disposable",
    desc: "RAYA D3 with a wide 20-flavor menu covering apple, grape, peach and ice classics.",
    options: unique([
      "Double Apple",
      "Grape Ice",
      "VMT",
      "Watermelon Lemon",
      "Watermelon Ice",
      "Strawberry Grape",
      "Peach Ice",
      "Peach Berry",
      "Mango Peach Watermelon",
      "Mango Peach",
      "Kiwi Passion Fruit Guava",
      "Grape Cherry",
      "Blueberry Raspberry",
      "Blueberry Ice",
      "Grape Mint",
      "Lemon Lime Ice",
      "Strawberry Ice",
      "Apple Peach",
      "Blue Razz Ice",
      "Blackberry Cranberry",
      "Strawberry Watermelon",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "25,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-raya-d3-25k"),
    puffs: "25K",
  },
  {
    id: "elfbar-gh33000-pro",
    name: "ELFBAR GH33000 PRO",
    brand: "ELFBAR",
    kind: "Disposable",
    desc: "GH33000 PRO — 33K puffs with pine, soda, mint and sour fruit profiles.",
    options: unique([
      "Raspberry Grapefruit Lemon",
      "Grapefruit Passion Guava",
      "Cherry Pomegranate Pineapple",
      "Apple Kiwi Ice",
      "Pine Needles",
      "Kiwi Pineapple Peach",
      "Lemon Lime",
      "Mountain Mint",
      "Watermelon Ice",
      "Grape Ice",
      "Sour Strawberry Dragonfruit",
      "Pomegranate Burst",
      "Pear Soda",
      "Blue Razz Ice",
      "Granny Cherry",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "33,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-gh33000-pro"),
    puffs: "33K",
  },
  {
    id: "elfbar-trio-40k",
    name: "ELFBAR Trio 40K",
    brand: "ELFBAR",
    kind: "Disposable",
    badge: "LOW",
    desc: "Trio 40K three-mode disposable. Limited warehouse stock — confirm allocation on your quote.",
    options: unique([
      "Strawberry Orange Lime",
      "LA Grape",
      "Pineapple Lime",
      "Peach Twist",
      "Blueberry POM Slushy",
      "Cool Menthol",
      "Raspberry Watermelon",
      "Orange Blast",
      "Sour Apple Ice",
      "Scary Berry",
      "Sakura Grape",
      "Sour Strawberry Dragonfruit",
      "Pomegranate Blast",
      "Black Mint",
      "Watermelon Ice",
      "Blue Razz Ice",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["Nicotine", "5%"],
      ["Stock", "Limited"],
    ],
    stock: "limited",
    image: img("elfbar-trio-40k"),
    puffs: "40K",
  },
  {
    id: "elfbar-gh23000",
    name: "ELFBAR GH23000",
    brand: "ELFBAR",
    kind: "Disposable",
    desc: "GH23000 with candy, jasmine, plum and classic ice flavors.",
    options: unique([
      "Watermelon Ice",
      "Sour Watermelon Candy",
      "Raspberry Watermelon Lemon",
      "Polar Mint",
      "Jasmine Raspberry",
      "Green Plum Sour Lime",
      "Green Apple Ice",
      "Grape Ice",
      "Blue Razz Ice",
      "Apple Pear",
      "Watermelon Cherry",
      "Strawberry Watermelon Bubble",
      "Strawberry Banana",
      "Purple Mint",
      "Cherry Cola",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "23,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-gh23000"),
    puffs: "23K",
  },
  {
    id: "elfbar-duke-30000",
    name: "ELFBAR DUKE 30000",
    brand: "ELFBAR",
    kind: "Disposable",
    badge: "OUT",
    desc: "DUKE 30000 — currently out of warehouse stock. Join the waitlist via a quote request.",
    options: unique([
      "Blue Razz Ice",
      "Cherry Burst",
      "Cherry Lemon",
      "Cranberry Pineapple",
      "Grape Pomegranate",
      "Lemon Lime",
      "Mountain Mint",
      "Pineapple White Peach",
      "Nordic Berry",
      "Sicilia Orange",
      "Sour Apple Ice",
      "Sour Blackberry Ice",
      "Sour Grape Ice",
      "Strawberry Kiwi",
      "Watermelon Ice",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "30,000"],
      ["Nicotine", "5%"],
      ["Stock", "Out of stock"],
    ],
    stock: "out",
    image: img("elfbar-duke-30000"),
    puffs: "30K",
  },
  {
    id: "elfbar-elfliq-30ml",
    name: "ELFBAR Elfliq 30ml",
    brand: "ELFBAR",
    kind: "E-Liquid",
    desc: "30 ml Elfliq bottled e-liquid, 5% nicotine. Broad flavor set covering soda, rose, ice and dessert notes.",
    options: unique([
      "Watermelon Cherry",
      "Strawberry Cherry Lemon",
      "Strawberry Banana",
      "Pink Lemonade Soda",
      "Green Grape Rose",
      "Cherry Lemon Peach",
      "Blueberry Raspberry Pomegranate",
      "Blue Razz Ice",
      "Sour Watermelon Gummy",
      "Raspberry Lychee",
      "Pineapple Ice",
      "Pineapple Colada",
      "Mango Peach",
      "Lemon Lime",
      "Jasmine Raspberry",
      "Grape Cherry",
      "Double Apple",
      "Cool Mint",
      "Blueberry Rose Mint",
      "Apple Pear",
      "Cherry Cola",
      "Strawberry Kiwi",
      "Strawberry Raspberry Cherry Ice",
      "Blackberry Lemon",
      "Blueberry Sour Raspberry",
      "Pink Lemonade",
      "Kiwi Passion Fruit Guava",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Volume", "30 ml"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("elfbar-elfliq-30ml"),
    puffs: "30 ml",
  },
  {
    id: "lost-mary-mt50000-turbo",
    name: "Lost Mary MT50000 Turbo",
    brand: "Lost Mary",
    kind: "Disposable",
    badge: "NEW",
    desc: "Lost Mary MT50000 Turbo — high-output disposable with berry, grape and splash flavors.",
    options: unique([
      "Cherry Burst",
      "Blackberry Raspberry Lime",
      "Blueberry Passion Fruit",
      "Lemon Soda",
      "Raspberry Blackcurrant",
      "Mixed Grape",
      "Mixed Guava",
      "Strawberry Raspberry Lemonade",
      "Wild Berry Frost",
      "Green Mango Raspberry",
      "Strawberry Splash",
      "Sour Apple Kiwi",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Nicotine", "5%"],
      ["Stock", "In stock"],
    ],
    stock: "in",
    image: img("lost-mary-mt50000-turbo"),
    puffs: "50K",
  },
  {
    id: "fumot-digital-box-12000",
    name: "Fumot Digital Box 12000",
    brand: "Fumot",
    kind: "Disposable",
    desc: "Digital Box 12000 with a 20 ml tank, 550 mAh rechargeable 18300 cell, 0.8 Ω mesh coil and about 60 flavors. Specify flavors on your quote.",
    options: nic,
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "12,000"],
      ["E-liquid", "20 ml"],
      ["Battery", "550 mAh · USB-C"],
      ["Coil", "0.8 Ω mesh"],
      ["Carton", "200 pcs · 18 kg · 69.1×32×23.8 cm"],
    ],
    stock: "in",
    image: img("fumot-digital-box-12000"),
    puffs: "12K",
  },
  {
    id: "fumot-tornado-15000",
    name: "Fumot Tornado 15000",
    brand: "Fumot",
    kind: "Disposable",
    desc: "Tornado 15000 — 25 ml, 850 mAh rechargeable, 0.9 Ω mesh, 26 flavors. Name flavors when you request a quote.",
    options: nic,
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "15,000"],
      ["E-liquid", "25 ml"],
      ["Battery", "850 mAh"],
      ["Coil", "0.9 Ω mesh"],
      ["Carton", "160 pcs · 18.5 kg"],
    ],
    stock: "in",
    image: img("fumot-tornado-15000"),
    puffs: "15K",
  },
  {
    id: "fumot-eco-4in1-80k",
    name: "Fumot ECO 4-in-1 80K",
    brand: "Fumot",
    kind: "Disposable",
    badge: "NEW",
    desc: "ECO 4-in-1 80K — four flavor chambers in one body. Nicotine 0 / 2 / 3 / 5%. Packed 100 pcs per carton (17 kg).",
    options: nic,
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "80,000"],
      ["Format", "4-in-1"],
      ["Nicotine", "0 / 2 / 3 / 5%"],
      ["Carton", "100 pcs · 17 kg"],
    ],
    stock: "in",
    image: img("fumot-eco-4in1-80k"),
    puffs: "80K",
  },
  {
    id: "jnr-alien-10k",
    name: "JNR Alien 10K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Compact Alien 10K disposable. Master carton 200 pcs (10 per inner), 395×388×290 mm, 19.9 kg.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "10,000"],
      ["Inner", "10 pcs"],
      ["Carton", "200 pcs · 19.9 kg"],
    ],
    stock: "in",
    image: img("jnr-alien-10k"),
    puffs: "10K",
  },
  {
    id: "jnr-falcon-16k",
    name: "JNR Falcon 16K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Falcon 16K — 10 per inner, 200 per master carton, 23.85 kg.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "16,000"],
      ["Inner", "10 pcs"],
      ["Carton", "200 pcs · 23.85 kg"],
    ],
    stock: "in",
    image: img("jnr-falcon-16k"),
    puffs: "16K",
  },
  {
    id: "jnr-falcon-x-18k",
    name: "JNR Falcon X 18K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Falcon X 18K with retail, inner and master packing. 200 pcs / 23.75 kg carton.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "18,000"],
      ["Unit", "53.5×31.5×110 mm · 110 g"],
      ["Carton", "200 pcs · 23.75 kg · 565×335×240 mm"],
    ],
    stock: "in",
    image: img("jnr-falcon-x-18k"),
    puffs: "18K",
  },
  {
    id: "jnr-mega-box",
    name: "JNR Mega Box",
    brand: "JNR",
    kind: "Disposable",
    desc: "Mega Box high-capacity disposable. 10 per inner, 200 per carton, 605×325×270 mm, 34.45 kg.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Format", "Mega Box"],
      ["Inner", "10 pcs"],
      ["Carton", "200 pcs · 34.45 kg"],
    ],
    stock: "in",
    image: img("jnr-mega-box"),
    puffs: "Mega",
  },
  {
    id: "jnr-shisha-max",
    name: "JNR Shisha Max",
    brand: "JNR",
    kind: "Disposable",
    desc: "Shisha Max hookah-style disposable. 5 pcs inner / 100 pcs master, 14.5 kg.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Unit", "208×42×131 mm"],
      ["Inner", "5 pcs · 680 g"],
      ["Carton", "100 pcs · 14.5 kg · 423×228×282 mm"],
    ],
    stock: "in",
    image: img("jnr-shisha-max"),
    puffs: "Shisha",
  },
  {
    id: "jnr-tank-pro",
    name: "JNR Tank Pro",
    brand: "JNR",
    kind: "Disposable",
    desc: "Tank Pro with a large visible tank. 10 per inner, 200 per carton, 24.62 kg.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Inner", "10 pcs"],
      ["Carton", "200 pcs · 24.62 kg · 587×292.5×266 mm"],
    ],
    stock: "in",
    image: img("jnr-tank-pro"),
    puffs: "Tank",
  },
  {
    id: "jnr-areo-x",
    name: "JNR Areo X",
    brand: "JNR",
    kind: "Pod System",
    desc: "TPD-certified 2 + 10 ml refillable pod system. Two refills for up to 32K puffs, 1.10 dual mesh, visible e-liquid.",
    options: ["2%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "Up to 32,000"],
      ["Fill", "2 ml pod + 10 ml bottle"],
      ["Coil", "1.10 dual mesh"],
      ["Cert", "TPD"],
      ["Carton", "100 devices + 200 bottles · ~15 kg"],
    ],
    stock: "in",
    image: img("jnr-areo-x"),
    puffs: "32K",
  },
  {
    id: "jnr-fox-10000",
    name: "JNR FOX 10000",
    brand: "JNR",
    kind: "Pod System",
    desc: "FOX 10000 — 2 ml prefilled pod plus 10 ml refill bottle, breathing light, Type-C, 800 mAh, 2% nicotine, TPD certified.",
    options: ["2%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "10,000"],
      ["Fill", "2 ml pod + 10 ml bottle"],
      ["Battery", "800 mAh · Type-C"],
      ["Nicotine", "2%"],
      ["Carton", "200 pcs · 18.35 kg"],
    ],
    stock: "in",
    image: img("jnr-fox-10000"),
    puffs: "10K",
  },
  {
    id: "jnr-falcon-pro",
    name: "JNR Falcon Pro 28K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Falcon Pro with a 30 ml tank, smart screen, dual mesh coil and 950 mAh Type-C battery. Nicotine 0 / 2 / 5%.",
    options: ["0%", "2%", "5%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "28,000"],
      ["E-liquid", "30 ml"],
      ["Battery", "950 mAh · Type-C"],
      ["Screen", "Smart display"],
      ["Carton", "100 pcs · 14.3 kg"],
    ],
    stock: "in",
    image: img("jnr-falcon-pro"),
    puffs: "28K",
  },
  {
    id: "jnr-panda",
    name: "JNR Panda",
    brand: "JNR",
    kind: "Pod System",
    desc: "Panda refillable kit: 2 ml prefilled pod and 10 ml bottle, 1.2 Ω dual mesh, 850 mAh.",
    options: ["2%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Fill", "2 ml pod + 10 ml bottle"],
      ["Coil", "1.2 Ω dual mesh"],
      ["Battery", "850 mAh"],
      ["Carton", "100 devices + 200 bottles · 14.8 kg"],
    ],
    stock: "in",
    image: img("jnr-panda"),
    puffs: "2+10 ml",
  },
  {
    id: "jnr-mega-box-pro",
    name: "JNR Mega Box Pro",
    brand: "JNR",
    kind: "Disposable",
    desc: "Mega Box Pro — 32 ml, 1.2 Ω dual mesh & dual core, 2% nicotine, 850 mAh. 100 pcs / 15.6 kg carton.",
    options: ["2%"],
    optionLabel: "NICOTINE",
    specs: [
      ["E-liquid", "32 ml"],
      ["Coil", "1.2 Ω dual mesh"],
      ["Battery", "850 mAh"],
      ["Nicotine", "2%"],
      ["Carton", "100 pcs · 15.6 kg"],
    ],
    stock: "in",
    image: img("jnr-mega-box-pro"),
    puffs: "Mega Pro",
  },
  {
    id: "jnr-shisha-hookah-70k",
    name: "JNR Shisha Hookah 70K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Hookah-style 70K disposable. 0.38 Ω single mesh, 1000 mAh, 6 mg/ml. 5 pcs inner, 100 pcs carton, 21.87 kg.",
    options: ["6 mg/ml"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "70,000"],
      ["Coil", "0.38 Ω mesh"],
      ["Battery", "1000 mAh"],
      ["Nicotine", "6 mg/ml"],
      ["Carton", "100 pcs · 21.87 kg · 565×310×420 mm"],
    ],
    stock: "in",
    image: img("jnr-shisha-hookah-70k"),
    puffs: "70K",
  },
  {
    id: "jnr-crown-shisha-100k",
    name: "JNR Crown Shisha 100K",
    brand: "JNR",
    kind: "Disposable",
    badge: "NEW",
    desc: "Crown Shisha 100K with triple 1.0 Ω mesh, 1300 mAh and 3% nicotine. 5 pcs / box, 100 pcs / carton.",
    options: ["3%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "100,000"],
      ["Coil", "Triple 1.0 Ω mesh"],
      ["Battery", "1300 mAh"],
      ["Nicotine", "3%"],
      ["Carton", "100 pcs · ~23.15 kg · 540×280×440 mm"],
    ],
    stock: "in",
    image: img("jnr-crown-shisha-100k"),
    puffs: "100K",
  },
  {
    id: "jnr-rage-gorilla-55k",
    name: "JNR Rage Gorilla 55K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Rage Gorilla 55K (also listed as Age Gorilla). 42 ml, dual mesh, 2% nicotine, 950 mAh.",
    options: ["2%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "55,000"],
      ["E-liquid", "42 ml"],
      ["Coil", "Dual mesh"],
      ["Battery", "950 mAh"],
      ["Carton", "100 pcs · 16.4 kg"],
    ],
    stock: "in",
    image: img("jnr-rage-gorilla-55k"),
    puffs: "55K",
  },
  {
    id: "jnr-windwhip-44000",
    name: "JNR WindWhip 44000",
    brand: "JNR",
    kind: "Disposable",
    desc: "WindWhip 44K with dual 20 ml tanks, smart screen, metal body, breathing light and adjustable airflow.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "44,000"],
      ["E-liquid", "2 × 20 ml"],
      ["Screen", "Smart display"],
      ["Carton", "200 pcs · 24.25 kg · 655×316×276 mm"],
    ],
    stock: "in",
    image: img("jnr-windwhip-44000"),
    puffs: "44K",
  },
  {
    id: "jnr-shisha-ultra-45000",
    name: "JNR Shisha Ultra 45K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Shisha Ultra 45K DTL disposable with leather exterior, 40 ml, 1100 mAh Type-C, 1.20 mesh with triple-mesh option, adjustable airflow and battery display.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "45,000"],
      ["E-liquid", "40 ml"],
      ["Battery", "1100 mAh · Type-C"],
      ["Body", "Leather"],
      ["Carton", "100 pcs · 13.9 kg"],
    ],
    stock: "in",
    image: img("jnr-shisha-ultra-45000"),
    puffs: "45K",
  },
  {
    id: "jnr-hexafuse-120k",
    name: "JNR HexaFuse 6-in-1 120K",
    brand: "JNR",
    kind: "Disposable",
    badge: "NEW",
    desc: "HexaFuse six-chamber 120K. 1.0 Ω coil, 800 mAh, 6 × 10 ml. 5 pcs / box, 100 pcs / carton, 17.25 kg.",
    options: ["Standard"],
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "120,000"],
      ["Format", "6 × 10 ml"],
      ["Coil", "1.0 Ω"],
      ["Battery", "800 mAh"],
      ["Carton", "100 pcs · 17.25 kg · 580×293×290 mm"],
    ],
    stock: "in",
    image: img("jnr-hexafuse-120k"),
    puffs: "120K",
  },
  {
    id: "jnr-lila-kiss-60k",
    name: "JNR Lila Kiss 60K",
    brand: "JNR",
    kind: "Disposable",
    desc: "Lila Kiss 60K kit. 24 ml, 0.6 Ω dual mesh, 2% nicotine, 1000 mAh Type-C. 10 pcs / box, 200 pcs / carton, 23 kg.",
    options: ["2%"],
    optionLabel: "NICOTINE",
    specs: [
      ["Puffs", "60,000"],
      ["E-liquid", "24 ml"],
      ["Coil", "0.6 Ω dual mesh"],
      ["Battery", "1000 mAh · Type-C"],
      ["Nicotine", "2%"],
      ["Carton", "200 pcs · 23 kg"],
    ],
    stock: "in",
    image: img("jnr-lila-kiss-60k"),
    puffs: "60K",
  },
  {
    id: "vozol-rave-40k",
    name: "VOZOL Rave 40K",
    brand: "Vozol",
    kind: "Disposable",
    desc: "Rave 40K — 1000 mAh, 20 ml, up to 40,000 puffs, 5%. 200 pcs / 25.5 kg carton.",
    options: unique([
      "Blue Razz Ice",
      "Blueberry Ice",
      "Blueberry Watermelon",
      "Cherry Cola",
      "Cherry Strawberry",
      "Cool Mint",
      "Double Apple",
      "Dragon Fruit Banana",
      "Grape Ice",
      "Kiwi Passion Fruit",
      "Love 777",
      "Mango Ice",
      "Mango Peach",
      "Peach Ice",
      "Peach Raspberry Lemonade",
      "Strawberry Ice",
      "Strawberry Kiwi",
      "Strawberry Mango",
      "Strawberry Watermelon",
      "Strawmelon Peach",
      "Watermelon Bubblegum",
      "Watermelon Ice",
      "Watermelon Razz Rancher",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["E-liquid", "20 ml"],
      ["Battery", "1000 mAh"],
      ["Nicotine", "5%"],
      ["Carton", "200 pcs · 25.5 kg · 560×265×365 mm"],
    ],
    stock: "in",
    image: img("vozol-rave-40k"),
    puffs: "40K",
  },
  {
    id: "vozol-vista-40k",
    name: "VOZOL Vista 40K",
    brand: "Vozol",
    kind: "Disposable",
    desc: "Vista 40K (50 mg) with 20 flavors. 1000 mAh, 20 ml, 200 pcs / 25.8 kg.",
    options: unique([
      "Blue Razz Ice",
      "Blueberry Ice",
      "Cherry Cola",
      "Double Apple",
      "Frozen Strawberry Kiwi",
      "Grape Ice",
      "Juicy Peach",
      "Love 777",
      "Lychee Orange Passion Fruit",
      "Mango Ice",
      "Mango Passion Fruit",
      "Mango Peach",
      "Melon Gum",
      "Miami Mint",
      "Passion Fruit Raspberry Tangerine",
      "Peach Berry",
      "Strawberry Banana",
      "Strawberry Watermelon",
      "Watermelon Bubble Gum",
      "Watermelon Ice",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["E-liquid", "20 ml"],
      ["Battery", "1000 mAh"],
      ["Nicotine", "50 mg"],
      ["Carton", "200 pcs · 25.8 kg"],
    ],
    stock: "in",
    image: img("vozol-vista-40k"),
    puffs: "40K",
  },
  {
    id: "vozol-star-40k",
    name: "VOZOL Star 40K",
    brand: "Vozol",
    kind: "Disposable",
    desc: "Star 40K (50 mg) — 23 flavors, 1000 mAh, 20 ml. Carton 200 pcs / 23.3 kg.",
    options: unique([
      "Blue Razz Ice",
      "Blueberry Ice",
      "Blueberry Mint",
      "Blueberry Watermelon",
      "Cherimoya Grapefruit Berries",
      "Cherry Cola",
      "Grape Ice",
      "Mango Ice",
      "Mango Peach",
      "Melon Gum",
      "Melon Ice",
      "Peach Ice",
      "Sour Apple Ice",
      "Strawberry Ice",
      "Strawberry Kiwi",
      "Strawberry Watermelon",
      "Strawmelon Peach",
      "Vzbull",
      "Watermelon Bubble Gum",
      "Watermelon Grape Boysenberry",
      "Watermelon Ice",
      "Watermelon Sour Peach",
      "White Peach Raspberry",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "40,000"],
      ["E-liquid", "20 ml"],
      ["Battery", "1000 mAh"],
      ["Nicotine", "50 mg"],
      ["Carton", "200 pcs · 23.3 kg"],
    ],
    stock: "in",
    image: img("vozol-star-40k"),
    puffs: "40K",
  },
  {
    id: "vozol-gear-50k",
    name: "VOZOL Gear Ice & Sweet 50K",
    brand: "Vozol",
    kind: "Disposable",
    desc: "Gear Ice & Sweet 50K — 30 flavors, 1100 mAh, 30 ml. 200 pcs / 26.8 kg carton.",
    options: unique([
      "Black Raspberry Smoothie",
      "Blue Razz Ice",
      "Blueberry Grapefruit",
      "Blueberry Ice",
      "Blueberry Watermelon",
      "Cherry Blackberry Orange",
      "Cherry Cola",
      "Coconut Melt Magic",
      "Cranberry Grape Juice",
      "Grape Ice",
      "Guava Melon Ice",
      "Love 777",
      "Mango Ice",
      "Mango Passion Tangerine",
      "Melon Gum",
      "Mixed Berries",
      "Peach Ice",
      "Peach Mango Watermelon",
      "Peach Pop Bliss",
      "Pineapple Squish",
      "Strawberry Banana",
      "Strawberry Kiwi",
      "Strawberry Raspberry Cherry",
      "Strawberry Watermelon",
      "Strawmelon Peach",
      "Super Mint",
      "Two Apples",
      "VCT",
      "Watermelon Bubble Gum",
      "Watermelon Ice",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["E-liquid", "30 ml"],
      ["Battery", "1100 mAh"],
      ["Nicotine", "50 mg"],
      ["Carton", "200 pcs · 26.8 kg"],
    ],
    stock: "in",
    image: img("vozol-gear-50k"),
    puffs: "50K",
  },
  {
    id: "vozol-star-click-50k",
    name: "VOZOL Star Click 50K",
    brand: "Vozol",
    kind: "Disposable",
    desc: "Star Click 50K with coffee, molasses and fruit clicks. 30 flavors, 1000 mAh, 100 pcs / 15 kg.",
    options: unique([
      "Arabic Coffee",
      "Blackberry Pomegranate Cherry",
      "Blue Razz Ice",
      "Blueberry Energy",
      "Cappuccino",
      "Cherry Cola",
      "Date Shake Molasses",
      "Dragonfruit Banana Cherry",
      "Grape Ice",
      "Love 777",
      "Melon Bubblegum",
      "Mexican Mango Ice",
      "Mixed Berry",
      "Orange Molasses",
      "Peach Ice",
      "Peach Mango Watermelon",
      "Pineapple Ice",
      "Raspberry Watermelon",
      "Spearmint",
      "Strawberry Banana",
      "Strawberry Gum",
      "Strawberry Kiwi",
      "Strawberry Lemon",
      "Strawberry Raspberry Cherry",
      "Strawberry Watermelon",
      "Tiger Blood",
      "Tropical Fruit Storm",
      "Watermelon Gum",
      "Watermelon Ice",
      "Watermelon Melon",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "50,000"],
      ["Battery", "1000 mAh"],
      ["Nicotine", "50 mg"],
      ["Flavors", "30"],
      ["Carton", "100 pcs · 15 kg"],
    ],
    stock: "in",
    image: img("vozol-star-click-50k"),
    puffs: "50K",
  },
  {
    id: "vozol-neon-60k",
    name: "VOZOL Neon 60K",
    brand: "Vozol",
    kind: "Disposable",
    badge: "NEW",
    desc: "Neon 60K — the catalog drop. 1100 mAh, up to 60,000 puffs, 5%, 30 flavors including coffee, molasses and ice. 100 pcs / 12.9 kg.",
    options: unique([
      "Blackberry Ice",
      "Blackberry Pomegranate Cherry",
      "Blue Razz Ice",
      "Blueberry Energy",
      "Cappuccino",
      "Cherry Cola",
      "Date Shake Molasses",
      "Dragonfruit Banana Cherry",
      "Grape Ice",
      "Iced Mint Tea",
      "Love 777",
      "Mango Ice",
      "Martinho",
      "Melon Bubblegum",
      "Mixed Berry",
      "Orange Ice",
      "Peach Ice",
      "Peach Mango Watermelon",
      "Pineapple Ice",
      "Raspberry Watermelon",
      "Spearmint",
      "Strawberry Banana",
      "Strawberry Gum",
      "Strawberry Kiwi",
      "Strawberry Raspberry Cherry",
      "Strawberry Watermelon",
      "Tiger Blood",
      "Watermelon Gum",
      "Watermelon Ice",
      "Watermelon Melon",
    ]),
    optionLabel: "FLAVOR",
    specs: [
      ["Puffs", "60,000"],
      ["Battery", "1100 mAh"],
      ["Nicotine", "5%"],
      ["Flavors", "30"],
      ["Carton", "100 pcs · 12.9 kg"],
    ],
    stock: "in",
    image: img("vozol-neon-60k"),
    puffs: "60K",
  },
];

export interface OrderItem {
  name: string;
  option: string;
  qty: number;
}

export interface Order {
  id: string;
  date: string;
  items: OrderItem[];
  status: "Quoted" | "Processing";
}

export const EU_COUNTRIES = [
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Austria",
  "Portugal",
  "Ireland",
  "Finland",
  "Denmark",
  "Sweden",
  "Poland",
  "Czechia",
  "Greece",
  "Hungary",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Croatia",
  "Luxembourg",
  "Estonia",
  "Lithuania",
  "Latvia",
  "Bulgaria",
];

export const FEATURED_ID = "vozol-neon-60k";

export const getProduct = (id: string) => PRODUCTS.find((p) => p.id === id);
export const GRID_PRODUCTS = PRODUCTS;
export const stockLabel = (s: Stock) =>
  s === "in" ? "In stock" : s === "limited" ? "Limited stock" : "Out of stock";
